name: Build & Release Commit Package

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      INCLUDE_PATHS: |
        assets/
        MyCTMLib.cfg
        pack.mcmeta
        pack.png
        README.md

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get short commit hash
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set up zip file
        run: |
          mkdir zip-root
          for path in $INCLUDE_PATHS; do
            cp -r --parents "$path" zip-root/
          done
          cd zip-root
          zip -r ../Modernity-GTNH-${SHORT_SHA}-pre.zip ./
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Commit ${{ env.SHORT_SHA }}
          tag_name: commit-${{ env.SHORT_SHA }}
          prerelease: true
          files: Modernity-GTNH-${{ env.SHORT_SHA }}-pre.zip
