name: Optimize PNG with Oxipng

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: write
  pull-requests: write

jobs:
  optimize-png:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install oxipng
        run: cargo install oxipng

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Prepare diff commits
        run: |
          EVENT_NAME="${{ github.event_name }}"
          if [ "$EVENT_NAME" = "pull_request" ]; then
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
            HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          else
            BASE_SHA="${{ github.event.before }}"
            HEAD_SHA="${{ github.sha }}"
          fi

          git fetch origin "$BASE_SHA" --depth=1 || true
          git fetch origin "$HEAD_SHA" --depth=1 || true

          echo "BASE_SHA=$BASE_SHA" >> $GITHUB_ENV
          echo "HEAD_SHA=$HEAD_SHA" >> $GITHUB_ENV

      - name: Optimize PNG files
        run: |
          echo "Base SHA: $BASE_SHA"
          echo "Head SHA: $HEAD_SHA"
          echo "Git log (last 5 commits):"
          git log --oneline -5

          echo "Changed PNG files between $BASE_SHA and $HEAD_SHA:"
          git diff --diff-filter=AMR --name-only -z "$BASE_SHA" "$HEAD_SHA" -- '*.png' > changed_pngs.txt || true

          if [ "$(wc -c < changed_pngs.txt)" -eq 0 ]; then
            echo "No PNG files changed."
            exit 0
          fi

          echo "Detected PNG changes:"
          tr '\0' '\n' < changed_pngs.txt

          echo "Optimizing PNGs..."
          while IFS= read -r -d '' file; do
            if [ -f "$file" ]; then
              echo "Optimizing: $file"
              oxipng -o 6 --alpha "$file"
            else
              echo "File not found: $file"
            fi
          done < changed_pngs.txt

      - name: Commit changes to new branch
        run: |
          BRANCH_NAME="oxipng-optimization-${{ github.run_id }}"
          git checkout -b "$BRANCH_NAME"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          xargs -0 git add < changed_pngs.txt

          if git diff --cached --quiet; then
            echo "No PNG optimization changes found."
            exit 0
          fi

          git commit -m "Optimize PNG images with oxipng"
          git push origin "$BRANCH_NAME"

          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create Pull Request
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          set -e
          gh auth login --with-token <<< "$GH_PAT"

          EVENT_NAME="${{ github.event_name }}"
          if [ "$EVENT_NAME" = "pull_request" ]; then
            TARGET_LABEL="PR #${{ github.event.pull_request.number }}"
            BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          else
            TARGET_LABEL="Commit ${{ github.sha }}"
            BASE_BRANCH="${{ github.ref_name }}"
          fi

          PNG_LIST=$(git diff --cached --name-only -- '*.png' || true)
          FILE_COUNT=$(echo "$PNG_LIST" | grep -c ".png$" || true)
          FILE_COUNT=${FILE_COUNT:-0}

          if [ "$FILE_COUNT" -eq 0 ]; then
            echo "No PNG files to commit, skipping PR creation."
            exit 0
          fi

          gh pr create \
            --base "$BASE_BRANCH" \
            --head "$branch_name" \
            --title "Optimize PNG images for $TARGET_LABEL" \
            --body "**Optimized PNG images for $TARGET_LABEL**\n\n**Total files optimized:** $FILE_COUNT\n\n**Files:**\n\`\`\`\n$PNG_LIST\n\`\`\`"
