name: Optimize PNG with Oxipng

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: write
  pull-requests: write

jobs:
  optimize-png:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install oxipng
        run: cargo install oxipng

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Optimize PNG files
        run: |
          CHANGED_PNGS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.png')
          if [ -z "$CHANGED_PNGS" ]; then
            echo "No PNG files changed."
            exit 0
          fi
          echo "Optimizing PNGs..."
          for file in $CHANGED_PNGS; do
            if [ -f "$file" ]; then
              oxipng -o 6 --alpha "$file"
            fi
          done

      - name: Commit changes to new branch
        run: |
          if git diff --quiet; then
            echo "No optimization changes found."
            exit 0
          fi

          BRANCH_NAME="oxipng-optimization-${{ github.run_id }}"
          git checkout -b "$BRANCH_NAME"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add '*.png'
          git commit -m "Optimize PNG images with oxipng"
          git push origin "$BRANCH_NAME"

          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e

          EVENT_NAME="${{ github.event_name }}"
          if [ "$EVENT_NAME" = "pull_request" ]; then
            TARGET_LABEL="PR #${{ github.event.pull_request.number }}"
            BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          else
            TARGET_LABEL="Commit ${{ github.sha }}"
            BASE_BRANCH="${{ github.ref_name }}"
          fi

          echo "Base branch: $BASE_BRANCH"
          echo "Target label: $TARGET_LABEL"

          git fetch origin "$BASE_BRANCH"

          PNG_LIST=$(git diff --name-only "origin/$BASE_BRANCH" -- '*.png' || true)
          FILE_COUNT=$(echo "$PNG_LIST" | grep -c ".png$" || echo 0)

          if [ "$FILE_COUNT" -eq 0 ]; then
            echo "No PNG files changed, skipping PR creation."
            exit 0
          fi

          gh pr create \
            --base "$BASE_BRANCH" \
            --head "$branch_name" \
            --title "Optimize PNG images for $TARGET_LABEL" \
            --body "**Optimized PNG images for $TARGET_LABEL**\n\n**Total files optimized:** $FILE_COUNT\n\n**Files:**\n\`\`\`\n$PNG_LIST\n\`\`\`"
