name: Optimize PNG files

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build-and-test:
    uses: GTNewHorizons/GTNH-Actions-Workflows/.github/workflows/optimize-images.yml@image_compression
    secrets: inherit