name: Optimize PNG files

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ "**" ]

jobs:
  build-and-test:
    uses: GTNewHorizons/GTNH-Actions-Workflows/.github/workflows/optimize-images.yml@image_compression
    secrets: inherit
